export const GAME_EVENT = {
    BET: 'GAME_EVENT.BET',
    WIN: 'GAME_EVENT.WIN',
    LOSE: 'GAME_EVENT.LOSE',
    RESET: 'GAME_EVENT.RESET',
    BET_PROGRESS: 'GAME_EVENT.BET_PROGRESS',
    BACKGROUND_CHANGE_STAGE: 'GAME_EVENT.BACKGROUND_CHANGE_STAGE',
    TOGGLE_FADE_MAIN_SOUND: 'GAME_EVENT.TOGGLE_FADE_MAIN_SOUND'
};

export const UI_EVENT = {
    BET: 'UI_EVENT.BET',
    BET_INCREASE: 'UI_EVENT.BET_INCREASE',
    BET_DECRASE: 'UI_EVENT.BET_DECRASE',
    TAKE: 'UI_EVENT.TAKE',
    AUTO_TAKE_INCREASE: 'UI_EVENT.AUTO_TAKE_INCREASE',
    AUTO_TAKE_DECRASE: 'UI_EVENT.AUTO_TAKE_DECRASE',
    AUTO_BET: 'UI_EVENT.AUTO_BET',
    AUTO_TAKE: 'UI_EVENT.AUTO_TAKE'
};

export const SOUND_EVENT = {
    POPUP_WIN: 'SOUND_EVENT.POPUP_WIN',
    POPUP_LOSE: 'SOUND_EVENT.POPUP_LOSE',
    TRANSITION_OPEN: 'SOUND_EVENT.TRANSITION_OPEN',
    TRANSITION_CLOSE: 'SOUND_EVENT.TRANSITION_CLOSE',
    MINE: 'SOUND_EVENT.MINE',
    BALLON: 'SOUND_EVENT.BALLON'
};
